class Supply {
    ctor Supply(water: f32, cookie: i32): water(water), cookie(cookie) {
    }
    
    water: f32;
    cookie: i32;
}

fn add_one_inplace(x: i32&): void {
    x += 1;
}
fn add_one(x: i32): i32 {
    return x + 1;
}

supply := Supply(1.2, 4);
supply.println();
supply.cookie = 5;
supply.println();
supply.cookie.add_one();
supply.println();
supply.cookie.add_one_inplace();
supply.println();

for i in 1..10 {
    print(i + " ");
}

#fn greet_tom(greeter: (str): str): void{
#    greeter("tom").println();
#}
#
#fn greet(x: str): str{
#    return "Greeting " + x + " from function";
#}

#greet_tom(greet);
#
#who := "";
#greet_tom([&who](x: str): str{ 
#    who = x;
#    return "Greeting " + x + " from lambda"; 
#});
#println("Greeted who?: " + who);