scene := Scene();
image_size := [360, 360];

#scene.add(DirectionalLight([1, 1, -1], [1, 1, 1]));
scene.set(ImageSky("scenes/hdr/cloudy.hdr", vec3(0.3), 0.0, 0.0));

scene.add(VDBMedium("scenes/vdb/cloud0.half.nvdb", rotate_y(-Pi / 2) * scale(vec3(0.003)), Hg2PF(0.85, -0.7, 0.1), 0.0, 100 * [1, 1, 1]));

scene.set(ThinLenCamera(Film(image_size), [-0.7, 0.1, 4], [0.1, 0.1, 0], 0.2));

PathIntegrator(HaltonSampler(1024 / 8), 1024).render(scene);
scene.camera.film().save("images/cloud.png");