scene := Scene();
image_size := [640, 640];

scene.add(Rect([0, 0, 0], [10, 0, 0], [0, 0, 10]), Diffuse(vec3(0.8)));
 
scene.add(Mesh("scenes/model/prism.pineb").apply(rotate_x(Pi / 2)), Glass(vec3(1.0), 0.0));

from := [-3, 2, 0];
to := [0, 2, 0];
scene.add(Disk(from, to - from, 0.5), Emissive(vec3(40)));

scene.set(ThinLenCamera(Film(image_size), [0, 4, -8], [0, 1, 0], 0.5));

PathIntegrator(BlueSampler(256), 6).render(scene);
scene.camera.film().save("images/dispersion1.png");
