scene = Scene();
image_size = [640, 360];

scene.add("diffuse", Diffuse([1, 1, 1]));

scene.add(Plane([0, 0, 0], [0, 1, 0]), "diffuse");
#scene.add(Box([-1, 0, -1], [1, 2, 1]), "diffuse");
#scene.add(Box([-1, 0, -1], [1, 2, 1]) + Box([0, 1, 0], [2, 3, 2]), "diffuse");
#scene.add(Box([-1, 0, -1], [1, 2, 1]) * Box([0, 1, 0], [2, 3, 2]), "diffuse");
scene.add(Box([-1, 0, -1], [1, 1, 1]) - Sphere([0, 1.5, 0], 1), "diffuse");
#scene.add(Box([-1, 0, -1], [1, 2, 1]) - Box([-1, 2, -1]/2.0, [1, 5, 1]/2.0), "diffuse");

scene.add(PointLight([0, 5, 0], 50 * [1, 1, 1]));

scene.set(ThinLenCamera(Film(image_size), [0, 4, -4] * 0.5, [0, 0, 0], 0.5));

PathIntegrator(BlueSampler(32), 2).render(scene);
scene.camera.film().save("images/pine.png");