scene := Scene();
image_size := [640, 640];


scene.add("ground", Diffuse([0.5, 0.5, 0.5]));
scene.add("floor", Diffuse([0.9, 0.9, 0.9]));
scene.add("red", Diffuse([0.9, 0.1, 0.05]));
scene.add("green", Diffuse([0.2, 0.9, 0.05]));

planet_r := 6360.0;
atmo_r := 6460.0;
scene.add(Sphere([0, 0, 0], planet_r), "ground");
scene.add(HomoMedium(Sphere([0, 0, 0], atmo_r), 0.0, 0.0001 * [5.802, 13.558, 33.1]));
scene.add(DirectionalLight([-8, .4, -10], 10.0));

#scene.add(Sphere(atmo_r * 20 * normalize([8, 1, -10]), 1000.0), Emissive([1, 1, 1] * 100000));

S := .5;
scene.add(Rect([S * 0,  planet_r + S * 0, S * 1], S * [2, 0, 0], S * [0, 0, 2]), "floor");
scene.add(Rect([S * 0,  planet_r + S * 2, S * 1], S * [2, 0, 0], S * [0, 0, 2]), "floor");
scene.add(Rect([S * -1, planet_r + S * 1, S * 1], S * [0, 0, 2], S * [0, 2, 0]), "red");
scene.add(Rect([S * 1,  planet_r + S * 1, S * 1], S * [0, 0, 2], S * [0, 2, 0]), "green");
scene.add(Rect([S * 0,  planet_r + S * 1, S * 2], S * [2, 0, 0], S * [0, 2, 0]), "floor");
add_box(scene, translate([S * -0.6, planet_r, S * 1.0]) * rotate_y(-0.4) * scale(S * [0.6, 1.3, 0.6]), "floor");
add_box(scene, translate([S * 0.0,  planet_r, S * 0.4]) * rotate_y(0.4) * scale(S * [0.6, 0.6, 0.6]), "floor");

scene.set(ThinLenCamera(Film(image_size), [0, planet_r + S, -S * 5], [0, planet_r + S, 0], 0.25));

PathIntegrator(HaltonSampler(64), 5).render(scene);
scene.camera.film().save("images/planet.png");