scene := Scene();
image_size := [640, 640];

scene.add("floor", Diffuse([1, 1, 1]));
#scene.add("skin", Glass([1, 1, 1], 0.1, 5.0));
scene.add("skin", Subsurface([1, 1, 1], 0.1, 1 * [1, 5, 10]));

scene.add(AABB([-4, -2, -4], [4, 0, 4]), "skin");
 
scene.add(Rect([0, 2, 0], [0.4, 0, 0], [0, 0, 0.4]), Emissive(30 * [1, 1, 1]));
#scene.add(SpotLight([0, 2, 0], [0, -1, 0], 10 * [1, 1, 1], 0.3));

scene.set(ThinLenCamera(Film(image_size, ACES()), [0, 2, -4], [0, 0, 0], 0.25));

PathIntegrator(BlueSampler(64), 5).render(scene);
scene.camera.film().save("images/sss.png");
